### ISSUE TITLE
Fix collaborative note and links to episodes on schedule

### ISSUE THREAD

**Issue by naoe-tatara** [uio-carpentry/2020-09-29-uio#4]
Sabry, please fix a link to collaborative note on index.md.

And if necessary, please make links to episodes on schedule. As you two taught together in February this year, I believe you coordinate well, but we experienced some miscommunication caused by time schedule not linked to lesson episodes before. Besides, this will be helpful for the learners,too. Lesson episodes are available at http://swcarpentry.github.io/git-novice/

**Comment by ghost** [comment]
The schedule items don't correspond directly with the episodes, there are more episodes. Should we instead put in all the episodes?

**Comment by naoe-tatara** [comment]
Sorry for a late response. Maybe the SWC's lesson schedule, which shows in total 3 hours is a bit too optimistic, but given that we have like at least 5 hours (9:00-16:00, minus lunch time and some breaks), would it be possible to cover all the episodes? But this is quite much up to you two; if it is best to go for exactly the same episodes covered in February and the same schedule, it is the best. What would you say @Sabryr ?
